# Generated by Django 3.1.5 on 2021-12-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restricted_endpoint_access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
