# Generated by Django 3.1.5 on 2021-12-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restricted_endpoint_access', '0002_userroles_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission_validators',
        ),
        migrations.RemoveField(
            model_name='role',
            name='request_injectors',
        ),
    ]
