# Generated by Django 3.1.5 on 2021-12-21 23:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restricted_endpoint_access', '0003_auto_20211220_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
