# Generated by Django 4.0.3 on 2022-03-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('date_activated', models.DateTimeField(auto_now_add=True)),
                ('date_registered', models.DateTimeField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_login_blocked', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('first_name', models.CharField(default=None, max_length=255, null=True)),
                ('last_name', models.CharField(default=None, max_length=255, null=True)),
                ('birth_date', models.DateField(default=None, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
